# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430fa4a68a65fa90ac5b7516828bfa1b95ce8cd02421224a5c655d5272e0d1b63b1f003bf3e60391f52f785c1505c70e1f89b70fcd6c02ea7bce6582a8fd155b

test:
  secret_key_base: cd24faf20483ca869d68efc5ce8539d40fd8557dfffbe0d4ef58a281e6fef2141a1a01fff4ca49b7b0ce12c1de4d7f3407d38be2c4006d669c2d558db94ad627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
